[platformio]
default_envs = esp32dev

[env]
build_flags = -std=gnu++17

[env:esp32dev]
platform = espressif32@^6.5.0
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
  adafruit/Adafruit ADS1X15
  adafruit/Adafruit BusIO@~1.16.0
  paulstoffregen/OneWire
  milesburton/DallasTemperature
  claws/BH1750
  links2004/WebSockets
  bblanchon/ArduinoJson@^6.21.5

[env:native]
platform = native
test_build_src = no
build_flags = -std=gnu++17
lib_deps =
  bblanchon/ArduinoJson@^6.21.5
